# Generated by Django 2.0.5 on 2018-10-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181021_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publishingdate',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
